apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ong-donation-webapi-ingress
  namespace: ong-donation
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx

  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ong-donation-webapi
            port:
              number: 80