apiVersion: v1
kind: Service
metadata:
  name: ong-donation-webapi
  namespace: ong-donation
spec:
  type: LoadBalancer
  selector:
    app: ong-donation-webapi
    component: api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP